### ISSUE TITLE
Aguinaldo!

### ISSUE THREAD

**Issue by manuel-cruz-itti** [noteregalesuwu/when_cobramos#1]
Necesitamos contador para el aguinaldo!

**Comment by noteregalesuwu** [comment]
@manuel-cruz-itti  _Nueva version desplegada! Gracias por la sugerencia 🏅_

**Comment by jkrauer** [comment]
Dice aguidaldo 😞

**Comment by noteregalesuwu** [comment]
@jkrauer Perdon, ya corregimos
