### ISSUE TITLE
Agregar contador de visitas

### ISSUE THREAD

**Issue by noteregalesuwu** [noteregalesuwu/when_cobramos#10]
@mykurevalija Doctor, puede ser pio un contador de visitas

**Comment by mykurevalija** [comment]
Dale, me pongo "patas" a la obra (?

**Comment by noteregalesuwu** [comment]
Se sube una primera version. La idea es que el contador sea con una db y no con link externo.

**Comment by noteregalesuwu** [comment]
Agregado en el nuevo sitio. Excelente desarrollo @mykurevalija
